# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('category', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
                ('hyperlink', models.CharField(max_length=1024)),
                ('archived', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
    ]
